spring:
  application:
    name: devHoard
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/devhoard}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

devhoard:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000