spring:
  application:
    name: devHoard
  datasource:
    url: jdbc:postgresql://localhost:5432/devhoard
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

devhoard:
  jwt:
    secret: 7d4b4f3b2a1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5
    expiration-ms: 86400000